data=[
    {
        tag_name:"标签序号1",
        link:null,
        position:20,
        x:0.62,
        y:0.88,
    },
    {
        tag_name:"标签序号2",
        link:null,
        position:20,
        x:0.54,
        y:0.32,
    },    
    {
        tag_name:"这是一个中间的标签",
        link:null,
        position:20,
        x:0.75,
        y:0.67,
    },
    {
        tag_name:"这是一个中间的标签",
        link:null,
        position:20,
        x:0.7,
        y:0.4,
    }

]